version: '3'

services:
  jwt-create:
    build:
      context: ./jwt-create
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  jwt-verify:
    build:
      context: ./jwt-verify
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  front-public:
    build:
      context: ./front-public
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge
